---
title: "課堂練習模版"
author: "tiffy"
date: "2020-10-28"
output: output_format
params:
  id: "410874206"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)
```
```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
```

```{r}
  '.台北市預報元素值' <- 
  list(
    city="台北市",
    high=25,
    low=18
  )
'.新北市預報元素值' <- 
  list(
    city="新北市",
    high=24,
    low=15
  )

library(lubridate)
'今明天氣' <-
  list(
    '今天日期'=ymd("2020-03-31"),
    '明天天氣'=ymd("2020-04-01"),
    '各地預報'=list(
      '.台北市預報元素值',
      '.新北市預報元素值'
      )

  )
```


```{r}
# 有多少名字可選：
names(listExample)

listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```

```{r}
vectorExample
vectorExample[c(1, 3)]

# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{R}
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```

